# See https://github.com/gruntwork-io/pre-commit
# Will need to install some pre-requisites
#       pre-commit      https://pre-commit.com/#install
#       tflint          https://github.com/terraform-linters/tflint/
# Can then install with
#       pre-commit install
# Can do a manual run with
#       pre-commit run

repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.9                                                 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: tflint 
        args: ["--deep", "--module"]
