
authorizer_lambda_s3_bucket   = ""
authorizer_lambda_s3_key      = ""
callback_lambda_s3_bucket     = ""
callback_lambda_s3_key        = ""
cso_lambda_s3_bucket          = ""
cso_lambda_s3_key             = ""
exposures_lambda_s3_bucket    = ""
exposures_lambda_s3_key       = ""
settings_lambda_s3_bucket     = ""
settings_lambda_s3_key        = ""
stats_lambda_s3_bucket        = ""
stats_lambda_s3_key           = ""
token_lambda_s3_bucket        = ""
token_lambda_s3_key           = ""

push_container_repo_url       = ""
api_container_repo_url        = ""
migrations_container_repo_url = ""

push_container_tag            = "latest"
api_container_tag             = "latest"
